### ISSUE TITLE
Class not found exception crash

### ISSUE THREAD

**Issue by TheonlyTazz** [AlmostReliable/summoningrituals-forge#11]
### Version

1.19.2 Fabric | summoningrituals-1.19.2-1.1.7

### Crash Report

https://gist.github.com/TheonlyTazz/298a70865548d73b94cc3c87eda53b29

### Additional Context

Yes

### Modifications

this was on the beta of LoTE
Quote from user:
`so I was about to spawn the one necromancer at the summoning alter in the nether and I was going to use the Spirit Shard to activate it. Well it had one zombie soul on it, and it keeps crashing the server now.`

### Did the crash happen in singleplayer or on a server?

Multiplayer

**Comment by rlnt** [comment]
Hm, yea. I know how to fix this but I won't be available until new year.

Thanks for the report.

**Comment by TheonlyTazz** [comment]
No worries! Have a great holiday ❤️
