### ISSUE TITLE
Support for ProbeJS

### ISSUE THREAD

**Issue by FooterManDev** [AlmostReliable/summoningrituals-forge#16]
### Describe the feature/addition!

Would it be possible to add full ProbeJS typings for the mod? The events can be picked up, but Recipes can't.

### Why would like to see this feature/addition?

Easier to code for KubeJS, without having to open the Wiki until it's imbued into your brain.

**Comment by Prunoideae** [comment]
Wait for KubeJS 6.1 to release, which will add a corresponding recipe description mechanism for ProbeJS to tap in without hardcoded documents (yes current recipes are all coded by me).

**Comment by FooterManDev** [comment]
Alrighty, I shall wait. Thanks for the response ✔️

**Comment by rlnt** [comment]
no shoo

**Comment by rlnt** [comment]
With the new update that will be available in a few minutes, the mod was updated to support KubeJS 6.1 and has proper ProbeJS integration now.
