### ISSUE TITLE
EMI integration

### ISSUE THREAD

**Issue by Kisuny** [AlmostReliable/summoningrituals-forge#25]
### Describe the feature/addition!

Displaying crafting in EMI.

EMI link - https://www.curseforge.com/minecraft/mc-mods/emi

### Why would like to see this feature/addition?

There is no way to figure out how to make an item/mob when u play with EMI mod.

**Comment by rlnt** [comment]
I thought this would already be working with the JEI compat EMI introduced. I've seen people using the mod with EMI, I am pretty sure. 🤔 
Do you use EMI without JEI?

**Comment by Kisuny** [comment]
Yes, you're really right, everything works with JEI
