### ISSUE TITLE
Block under Altar doesnt render in JEI

### ISSUE THREAD

**Issue by TheonlyTazz** [AlmostReliable/summoningrituals-forge#7]
### Version

summoningrituals-1.18.2-1.1.2.jar

### Describe the bug!

![image](https://user-images.githubusercontent.com/3908847/193471889-b5b2f8c0-062c-42f0-b5f7-9c5d3e899eb1.png)

this is on FTB Inferno 1.0.2 Dev

also tried with a vanilla block (minecraft:dirt) but that also doesnt render

### Crash Report

no crash report

### Log

no log

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
![](https://i.imgur.com/D9mgx5H.png)
![](https://i.imgur.com/uphIj9t.png)

I can't reproduce this, tested it in dev and in prod.
Can you show me the script/recipe you are using and send me your `latest.log`?

Also tested it with OptiFine, Rubidium and Oculus, no issues on my side.

**Comment by Saereth** [comment]
the recipe is
```

        //Witherstorm
        event.recipes.summoningrituals
        .altar('avaritia:infinity_ingot')
        .mobOutput(
            SummoningOutput.mob('witherstormmod:wither_storm')
            .offset(0, 10, 0)
            .count(1)
        )

        .input('bloodmagic:dungeon_metal')
        .input('inferno:purifiedinfernalessence')
        .input('ars_nouveau:glyph_wither')
        .input(Item.of('productivebees:configurable_comb', '{EntityTag:{type:"productivebees:withered"}}'))
        .input('reliquary:witherless_rose')
        .sacrifice('minecraft:wither')
        .sacrificeRegion(5, 5)
        .blockBelow('inferno:pseudo_command_block')
        .dayTime('night')
        .weather('thunder')
        .recipeTime(200)
```
The block is a custom block added by kubejs but we also tried it with dirt.

**Comment by rlnt** [comment]
I tested it in FTB Inferno and it's reproducible there but not in a minimal environment. It's unrelated to the current build and also happens with an older version of the mod.

Pretty sure this might be a conflicting mod but I don't have the time to do a binary search in FTB Inferno. However, I managed to work around this.
